### ISSUE TITLE
It prints weird stuff

### ISSUE THREAD

**Issue by xzores** [DaseinPhaos/pdb#5] opened 2023-03-09 18:00 UTC
For me the example project prints:
```
command: odin run .    

foo..
0
0
0
0
0
0
0
0
D:/pdb/demo.odin(22:18) Index 8 is out of range 0..<8
ExceptionType: 0xc000008c, Flags: 0x80 Stacktrace:12
C:\Windows\System32\KERNELBASE.dll(0:0)()
D:\pdb\pdb.exe(0:0)()
D:\pdb\pdb.exe(0:0)()
D:\pdb\pdb.exe(0:0)()
D:\pdb\pdb.exe(0:0)()
D:\pdb\pdb.exe(0:0)()
D:\pdb\pdb.exe(0:0)()
D:\pdb\pdb.exe(0:0)()
D:\pdb\pdb.exe(0:0)()
D:\pdb\pdb.exe(0:0)()
C:\Windows\System32\KERNEL32.DLL(0:0)()
```

**Comment by ftphikari** [comment] 2023-03-09 18:33
One is supposed to have debug info available, so `-debug` is mandatory. In fact, @DaseinPhaos might want to make it a requirement? It's quite bizzare seeing an empty stacktrace, it should just not print anything or say "if you want stacktrace compile with -debug" type thing.

**Comment by xzores** [comment] 2023-03-09 19:36
i did try with -debug, it did the same

**Comment by ftphikari** [comment] 2023-03-09 21:59
Can you send minimal example then?

**Comment by DaseinPhaos** [comment] 2023-03-10 12:06
> i did try with -debug, it did the same

It's not exactly the same here on my machine: 

```text
J:\repos\pdb>odin run . -debug
D:\a\Odin\Odin\src\llvm_backend_type.cpp(12): Panic: NOT FOUND lb_type_info_index ModStreamHeader @ index 493
```

seems like the latest odin build failed to generate debug info for the demo. Reproducible with `odin-windows-amd64-dev-2023-02` and `odin-windows-amd64-dev-2023-03`, but not the 2023-01 build. I'll see if I can produce a minimal repro and file an issue.
You might want to revert to the 2023-01 monthly build if you want the demo to work.

**Comment by DaseinPhaos** [comment] 2023-03-10 12:17
> One is supposed to have debug info available, so `-debug` is mandatory. In fact, @DaseinPhaos might want to make it a requirement? It's quite bizzare seeing an empty stacktrace, it should just not print anything or say "if you want stacktrace compile with -debug" type thing.

added in https://github.com/DaseinPhaos/pdb/commit/5cfea525748df3c2162c3fd58c140f942d85c3f8

**Comment by ftphikari** [comment] 2023-03-10 12:32
On latest master debug builds are completely broken, one needs to also add `-show-timings -thread-count=1`, `thread-count` makes it work at least sometimes, and `show-timings` will print timings if it compiled successfully, because if it crashes there is no output so you wouldn't know if it compiled or not.

**Comment by DaseinPhaos** [comment] 2023-03-10 13:49
issue filed: https://github.com/odin-lang/Odin/issues/2374#issuecomment-1463826590

**Comment by DaseinPhaos** [comment] 2023-05-23 20:06
Closed by https://github.com/DaseinPhaos/pdb/commit/154951d76938c76680201d4a4d1be0954aa5c0ab

**Closed as completed by DaseinPhaos** 2023-05-23 20:06 UTC
